---

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/xenial64
  - name: ubuntu/trusty64
  - name: centos/7
  - name: centos/6
  - name: debian/jessie64
  - name: debian/wheezy64

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[cop_users]
    attributes:
      users:
        user_list:
          - alice
          - bob
          # NOTE: omitting user "carol" for tests
          - dan
          # NOTE: including user without data bag
          - ed
          - francis
        group_list:
          - sudo
          - engineers
          - umbrella
